Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -18,13 +18,31 @@ jobs:
         with:
           terraform_version: 1.9.3  # Specify the Terraform version
           
-      - name: installing AWS CLI
+      - name: Install AWS CLI
         run: |
-            curl "https://d1uj6qtbmh3dt5.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+          # Update package list and install unzip
+          sudo apt-get update -y
+          sudo apt-get install -y unzip
+          
+          # Download AWS CLI v2 installer
+          curl -L "https://d1uj6qtbmh3dt5.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+          
+          # Verify the file was downloaded
+          if [ -s awscliv2.zip ]; then
+            echo "Download successful, starting unzip..."
             unzip awscliv2.zip
-            sudo ./aws/install  
-            aws --version
+          else
+            echo "Download failed or file is empty."
+            exit 1
+          fi
         
+          # Install AWS CLI
+          sudo ./aws/install
+          
+          # Verify AWS CLI installation
+          aws --version
+  
+          
       - name: Terraform Init
         run: terraform init -reconfigure
 
